# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  watch:
    types: [started]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - uses: actions/checkout@v1
    
    - name: Use Node.js 12.18.0
      uses: actions/setup-node@v1
      with:
        node-version: 12.18.0

    - name: Installing dependencies
      run: npm install
      
    - name: Building the Application
      env:
        API_URI: ${{ secrets.API_URI }}
        STATIC_URL: ${{ secrets.STATIC_URL }}
      run: npm run build
    
    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --delete
      env:
        API_URI: ${{ secrets.API_URI }}
        STATIC_URL: ${{ secrets.STATIC_URL }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: 'dist'
